const data = {
    products:[
        {
            _id:'1',
            name: 'Microlote Tribos',
            category: 'Café torrado em grãos',
            image:'/images/cafe1.png',
            price: 22,
            brand: '3 Corações',
            rating: 4.5,
            numReviews: 12,
            description: 'Café especial cultivado por indígenas',
            productor: 'Zé Guarani',
            region: 'Serra da Mantiqueira',
            pontuation: 88,
        },
        {
            _id:'2',
            name: 'Microlote Tribos',
            category: 'Café torrado em grãos',
            image:'/images/cafe1.png',
            price: 18,
            brand: '3 Corações',
            rating: 3.8,
            numReviews: 12,
            description: 'Café especial cultivado por indígenas',
            productor: 'Zé Guarani',
            region: 'Serra da Mantiqueira',
            pontuation: 88,
        },
        {
            _id:'3',
            name: 'Microlote Tribos',
            category: 'Café torrado em grãos',
            image:'/images/cafe1.png',
            price: 18,
            brand: '3 Corações',
            rating: 3.8,
            numReviews: 12,
            description: 'Café especial cultivado por indígenas',
            productor: 'Zé Guarani',
            region: 'Serra da Mantiqueira',
            pontuation: 88,
        },
        {
            _id:'4',
            name: 'Microlote Tribos',
            category: 'Café torrado em grãos',
            image:'/images/cafe1.png',
            price: 18,
            brand: '3 Corações',
            rating: 3.8,
            numReviews: 12,
            description: 'Café especial cultivado por indígenas',
            productor: 'Zé Guarani',
            region: 'Serra da Mantiqueira',
            pontuation: 88,
        },
        {
            _id:'5',
            name: 'Microlote Tribos',
            category: 'Café torrado em grãos',
            image:'/images/cafe1.png',
            price: 18,
            brand: '3 Corações',
            rating: 3.8,
            numReviews: 12,
            description: 'Café especial cultivado por indígenas',
            productor: 'Zé Guarani',
            region: 'Serra da Mantiqueira',
            pontuation: 88,
        },
        {
            _id:'6',
            name: 'Microlote Tribos',
            category: 'Café torrado em grãos',
            image:'/images/cafe1.png',
            price: 18,
            brand: '3 Corações',
            rating: 3.8,
            numReviews: 12,
            description: 'Café especial cultivado por indígenas',
            productor: 'Zé Guarani',
            region: 'Serra da Mantiqueira',
            pontuation: 88,
        },
    ],
};

export default data;
